title: Devportal - RSK Developer Portal | Rootstock (RSK)

description: >
  Rootstock (RSK) is the first open source Smart Contract platform secured by the
  Bitcoin Network. Rootstock adds value and expands the functionality of the
  Bitcoin ecosystem by providing smart contracts and greater scalability.

collections:
  quick-start:
    sort_by: collection_order
    output: true
  rsk:
    sort_by: collection_order
    output: true

rss: rss

breadcrumbs:
  root:
    hide: true
    image: false

permalink: pretty

repository: rsksmart/rsksmart.github.io

domain: "dev.rootstock.io"
url: "https://dev.rootstock.io"
redirect_base: ""
redirect_time: 0

highlighter: rouge

github: [metadata]

exclude:
  - .jekyll-cache
  - .bundle
  - vendor
  - assets/img/windowsInstall/
  - node_modules
  - package.json
  - README.md

plugins:
 - jekyll-last-modified-at
 - jekyll-feed
 - jekyll-sitemap
 - jemoji
